apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-frontend
spec:
  selector:
    matchLabels:
      app: fk-frontend
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fk-frontend
    spec:
      containers:
      - name: fk-frontend
        image: toresbe/fk-frontend:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
