apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: matrixorg
type: Opaque
data:
  POSTGRES_DB: c3luYXBzZQ== # synapse
  POSTGRES_USER: ZGJ0ZXN0 # dbtest
  POSTGRES_PASSWORD: ZGJ0ZXN0 # dbtest
